version: '3.8'

services:
  api:
    container_name: yeme_api_prod
    build:
      context: .
      target: production
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    env_file:
      - .env.production
    networks:
      - yeme-network-prod
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: yeme_postgres_prod
    image: postgres:15
    networks:
      - yeme-network-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    restart: always

networks:
  yeme-network-prod:

volumes:
  postgres_data_prod:
